-- Practicas con consultas simples
-- base de datos Sakila
-- 17-06-2024
-- Nombre: 
## 1. CONSULTAR TODAS LAS PELÍCULAS 
## 2. CONSULTAR LOS TÍTULOS DE TODAS LAS PELÍCULAS (FILM)
## 3. CONSULTAR NOMBRE Y APELLIDO DE LA TABLA ACTOR
## 4. CONSULTA STORE_ID, FIRST_NAME Y LAST_NAME DE LA TABLA CUSTOMER DE LA BASE DE DATOS SAKILA.
## 5. CAMBIA EL NOMBRE DE LAS COLUMNAS STORE_ID, FIRST_NAME Y LAST_NAME A TIENDA, NOMBRE Y APELLIDO RESPECTIVAMENTE.
## 6. ORDENA DE MANERA DESCENDENTE LA COLUMNA APELLIDO TABLA CUSTOMER
## 7. CONSULTA LA TABLA PAYMENT DE LA BASE DE DATOS SAKILA.
## 8. ¿CUÁL ES LA CANTIDAD MÁS BAJA Y MÁS ALTA DE LA COLUMNA AMOUNT?
## 9. CONSULTA DESCRIPTION, RELEASE_YEAR DE LA TABLA FILM DE LA BASE DE DATOS SAKILA  Y FILTRA LA INFORMACIÓN DÓNDE TITLE SEA IMPACT ALADDIN
## 10. CONSULTA LA TABLA PAYMENT DE LA BASE DE DATOS SAKILA MUESTRA LA INFORMACIÓN DONDE AMOUNT SEA MAYOR A 0.99.
## 11. CONSULTA LA TABLA FILM_TEXT DE LA BASE DE DATOS SAKILA, FILTRA LA INFORMACIÓN DÓNDE TITLE  SEA ZORRO ARK, VIRGIN DAISY, UNITED PILOT
##12.CONSULTA LA TABLA CITY DE LA BASE DE DATOS SAKILA FILTRA LA INFORMACIÓN DONDE CITY SEA CHIAYI, DONGYING, FUKUYAMA Y KILIS.
## 13.CONSULTA LA TABLA CITY DE LA BASE DE DATOS SAKILA FILTRA LA INFORMACIÓN 
## DONDE CITY NO SEA CHIAYI, DONGYING, FUKUYAMA Y KILIS.
## 14. CONSULTA LA TABLA PAYMENT DE LA BASE DE DATOS SAKILA FILTRA LA INFORMACIÓN 
## DONDE AMOUNT ESTÉ ENTRE 2.99 Y 4.99,  STAFF_ID SEA IGUAL A 2 Y CUSTOMER_ID SEA 1 Y 2
################ Dos tablas sin JOIN
# CONSULTAR LAS PELICULAS Y LOS ACTORES QUE TRABAJAN EN ELLA
# CONSULTAR LAS PELICULAS EN LAS QUE TRABAJA PENELOPE GUINNESS

